name: "nombresArchivos"
description: "no permite mayúsculas, espacios y acentos en nombres de archivo"
author: "piruetasxyz"
branding: 
  color: purple
  icon: file
  

inputs:
  pattern:
    description: "Regex for invalid filenames"
    required: false
    default: '[A-Z]|[ ]|[áéíóúÁÉÍÓÚ]'

  ignore:
    description: "Regex for files to ignore"
    required: false
    default: '^README\.md$'

runs:
  using: "composite"
  steps:
    - name: Check filenames
      shell: bash
      run: |
        files=$(git ls-files)

        # Remove ignored files
        if [ -n "${{ inputs.ignore }}" ]; then
          files=$(echo "$files" | grep -Ev "${{ inputs.ignore }}")
        fi

        invalid=$(echo "$files" | grep -E "${{ inputs.pattern }}" || true)

        if [ -n "$invalid" ]; then
          echo "❌ nombresArchivosMal:"
          echo "$invalid" | sed 's/^/ - /'
          exit 1
        fi

        echo "✅ nombresArchivosBien"
